### ISSUE TITLE
Please tag version 3.0.0

### ISSUE THREAD

**Issue by dbohdan** [lynn/elm-arithmetic#3]

**Comment by lynn** [comment]
Hello! I just got out of _exam hell_. I'm going to install the new Elm version and tag version 3.0.0 when I find the time. :)

**Comment by dbohdan** [comment]
Great!

**Comment by lynn** [comment]
I finally tagged it (but `elm-package` decided the 0.17 fix-up was a minor patch). Sorry for the delay!
